In [1]:
import numpy as np

### 행렬의 차원을 변경

In [2]:
# 1차원 행렬을 생성한다. 
array1 = np.arange(15)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
# 1차원 -> 2차원으로 변환
array2 = array1.reshape(3, 5)
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
# 2차원 -> 1차원    (-1)
array3 = array2.reshape(15)
display(array3)

array4 = array2.reshape(-1)
display(array4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 통계함수

In [12]:
array1 = np.arange(15).reshape(3, 5)
array1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
# 행렬이 제공하는 함수 사용하기 
mean1 = array1.mean()
# numpy가 제공하는 함수 사용하기 
mean2 = np.mean(array1)

print(mean1)
print(mean2)

7.0
7.0


### 로또 번호 추첨해보기...

In [15]:
# 1 ~ 45까지 가지
array1 = np.arange(1, 45)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [18]:
for _ in range(10):
    array2 = np.random.permutation(array1)
    array3 = array2[:6]
    array3.sort()
    display(array3)

array([ 6,  7, 12, 17, 31, 36])

array([ 5, 10, 18, 26, 28, 32])

array([16, 25, 32, 34, 38, 40])

array([ 1, 12, 14, 29, 34, 39])

array([ 9, 12, 14, 25, 27, 44])

array([ 2,  4,  7, 29, 31, 41])

array([12, 23, 31, 34, 38, 41])

array([ 3,  4, 11, 29, 31, 39])

array([ 6, 13, 18, 27, 34, 36])

array([ 4,  8, 19, 20, 22, 41])