In [4]:
x = [1, 2, 3, 4, 6]

# x*2 --> [1, 2, 3, 4, 6, 1, 2, 3, 4, 6]

for i in x:
    y = 2*i +1
    print(y)
    
y = [2*i for i in x]

3
5
7
9
13


In [6]:
y = []
for i in x:
    y.append(2*i + 1)
print(y)

y = [2*i | 1 for i in x]
print(y)

[3, 5, 7, 9, 13]
[3, 5, 7, 9, 13]


In [7]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 7])
y = 2*x + 1
print(y)

[ 3  5  7  9 11 15]


# 1. 오차의 이해

In [15]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([3, 6, 7, 9, 12])

w = 2
b = 1

# MSE
# np.sum((w*x + b - y)**2) / 5
e1 = np.mean((w*x +b -y)**2)
print(e1)

w =3
b = 0.1
e2 = np.mean((w*x + b -y)**2)
print(e2)

0.4
4.729999999999999


# 2. 행렬 기초

In [23]:
a = np.array([         [1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]
              ])
print(a)

b = a * 10 + 5
print(b)

c = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0]
])
print(c)

d = a * c + b + 3
print(d)

a = np.array([[1, 2], [3, 4]])
b = np.array([[3, 4], [7, 8]])
print(a*b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[15 25 35]
 [45 55 65]
 [75 85 95]]
[[0 0 1]
 [1 0 0]
 [0 1 0]]
[[18 28 41]
 [52 58 68]
 [78 96 98]]
[[ 3  8]
 [21 32]]


# 행렬연산

In [28]:
I = np.eye(3)
print(I)

b = 5 * a
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]


In [29]:
a = np.array([1, 2],
                [3, 4])

b = np.array([1, 2],
                [3, 4],
                [7, 8])

c = np.matmul(a, b) # 2by2 2by2 = 2by2
print(c)

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [31]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.matmul(I, a)  # 3by3 3by3 = 3by3


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

# 역행렬

In [37]:
a = np.array([[1, 1], 
                 [2, 1]])

inv = np.linalg.inv(a)
print(inv)

print(np.matmul(inv, a))

[[-1.  1.]
 [ 2. -1.]]
[[1. 0.]
 [0. 1.]]


In [38]:
a = np.array([[13, 2], 
                 [2, 1]])

inv = np.linalg.inv(a)
print(inv)

print(np.matmul(inv, a))

[[ 0.11111111 -0.22222222]
 [-0.22222222  1.44444444]]
[[ 1.0000000e+00  0.0000000e+00]
 [-4.4408921e-16  1.0000000e+00]]


# 역행렬을 이용한 최적해

In [42]:
A = np.array([[1, 1], 
              [2, 1]])
y = np.array([[2], 
              [4.4]]) 

inv = np.linalg.inv(A)
W = np.matmul(inv, y)
print(W)

[[ 2.4]
 [-0.4]]


In [45]:
w = W[0]
b = W[1]
print(w[0])
print(b[0])

2.4000000000000004
-0.40000000000000036


In [46]:
w = W[0][0]
b = W[1][0]
w, b

(2.4000000000000004, -0.40000000000000036)

In [47]:
w = W[0, 0]
b = W[1, 0]
w, b

(2.4000000000000004, -0.40000000000000036)

In [48]:
x = 7
h = w * x + b
print(h)

16.400000000000006


In [56]:
x = np.array([6, 7, 8, 10])
h = w * x + b
print(h)
print(type(w))

[14.  16.4 18.8 23.6]
<class 'numpy.float64'>


In [55]:
x = [6, 7, 8, 10]
h = W[0] * x + b
print(h)
print(type(W[0]))

[14.  16.4 18.8 23.6]
<class 'numpy.ndarray'>


In [58]:
x = np.array([[7, 1],
                 [8, 1],
                 [9, 1]])

h = np.matmul(x, W)
print(h)

[[16.4]
 [18.8]
 [21.2]]


# 의사역행렬

In [63]:
a = np.array([[1,1],
             [2,1],
             [3,1]])
y = np.array([[2], 
              [4],
              [6.4]])

pinv  = np.linalg.pinv(a)
print(pinv)

np.matmul(pinv, a)


[[-5.00000000e-01 -3.19189120e-16  5.00000000e-01]
 [ 1.33333333e+00  3.33333333e-01 -6.66666667e-01]]


array([[ 1.00000000e+00, -2.22044605e-16],
       [-4.44089210e-16,  1.00000000e+00]])

In [74]:
a = np.array([[1,1],
             [2,1],
             [3,1]])
y = np.array([[2], 
              [4],
              [6.4]])

y = np.array([2, 4, 6.4]).reshape(3, 1)
y = np.array([2, 4, 6.4]).reshape(-1, 1)
y = np.array([[2, 4, 6.4]]).T
# y = np.array([2, 4, 6.4]).T  --> 이거 안됨!!!

pinv  = np.linalg.pinv(a)
print(pinv)

np.matmul(pinv, a)

W = np.matmul(pinv, y)
print(W)

[[-5.00000000e-01 -3.19189120e-16  5.00000000e-01]
 [ 1.33333333e+00  3.33333333e-01 -6.66666667e-01]]
[[ 2.2       ]
 [-0.26666667]]


In [75]:
print(a)
mse = np.mean((np.matmul(a, W) - y)**2)
print(mse)

[[1 1]
 [2 1]
 [3 1]]
0.008888888888888925


# 택시비 추정하기

- a회사 : 1km 8000    2km 9200    3km 12000
- b회사 : 1km 5000    2km 8500    3km 11900
- 20km? 


In [85]:
# 수학자
# 문제 -> 수학적 모델링    ,    행렬식변화,    역행렬
# 개발자 -> 코딩

A = np.array([ [1, 1],
                    [2, 1],
                    [3, 1]])

y_A = np.array([8000, 9200, 12000]).reshape(-1, 1)
y_B = np.array([5000, 8500, 11000]).reshape(-1, 1)

pinv = np.linalg.pinv(A)

W_A = np.matmul(    pinv,    y_A    )
W_B = np.matmul(    pinv,    y_B    )
print(W_A)
print(W_B)

x = np.array([[20, 1]])
np.matmul(x, W_A), np.matmul(x, W_B)

#  2000x + 5733 = 3000x + 2166

[[2000.        ]
 [5733.33333333]]
[[3000.        ]
 [2166.66666667]]


(array([[45733.33333333]]), array([[62166.66666667]]))

[이자율, 실업률]  -  주가

- [3.4, 1.5 ... ]  1900
- [2.1, 2.5 ... ]  1700

y = w1*이자율 + w2*실업률 + b

- [3.4  1.5  1]        1900
- [2.1  2.5  1] -1    1700
- [3.4  2.1  1]        1500
- [1.7  2.4  1]        1000

- (4x3)-1 * 4*1
- (3x4)  (4x1)  =  3x1

# 주가 분석

In [ ]:
[이자율, 실업률]   -  주가

[3.4,  1.5   .. ] 1900
[2.1,  2.5   .. ] 1700
y = w1*이자율 + w2*실업률 + b*1

[3.4 1.5 1]          1900
[2.1 2.5 1] -1       1700
[3.4 2.1 1]          1500
[1.7 2.4 1]          1000

(4x3)-1 * 4*1 
(3x4) (4x1) = 3x1

In [ ]:
# 이자율, 실업률
ir  = [2.75,2.5,2.5,2.5,2.5,2.5,2.5,2.25,2.25,2.25,2,2,2,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75],
ur =  [5.3,5.3,5.3,5.3,5.4,5.6,5.5,5.5,5.5,5.6,5.7,5.9,6,5.9,5.8,6.1,6.2,6.1,6.1,6.1,5.9,6.2,6.2,6.1]
y = [1464,1394,1357,1293,1256,1254,1234,1195,1159,1167,1130,1075,1047,965,943,958,971,949,884,866,876,822,704,719]     


이자율 4.5%, 실업률 2.1일때 주가는?


In [114]:
A = np.hstack((np.array(ir).reshape(-1,1), 
               np.array(ur).reshape(-1,1), 
               np.ones((24,1))  ))
W = np.matmul(np.linalg.pinv(A), np.array(y).reshape(-1,1))
print(W)
X = [[4.5, 2.1, 1]]
np.matmul(X, W)

[[ 345.54008701]
 [-250.14657137]
 [1798.40397763]]


array([[2828.0265693]])

In [115]:
# 이자율, 실업률

A =  [ [2.75,2.5,2.5,2.5,2.5,2.5,2.5,2.25,2.25,2.25,2,2,2,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75],
       [5.3,5.3,5.3,5.3,5.4,5.6,5.5,5.5,5.5,5.6,5.7,5.9,6,5.9,5.8,6.1,6.2,6.1,6.1,6.1,5.9,6.2,6.2,6.1],
       [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]]
A = np.array(A).T
y = [1464,1394,1357,1293,1256,1254,1234,1195,1159,1167,1130,1075,1047,965,943,958,971,949,884,866,876,822,704,719]     
y = np.array(y).reshape(-1, 1)

<ipython-input-115-6f50001621cf>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  A = np.array(A).T


# 미분

In [118]:
a = [4, 5, 6, 10]
b = [5-4, 6-5,  10-6]
print(a)
print(b)

[4, 5, 6, 10]
[1, 1, 4]


In [120]:
def f(x):
    return 4*x + 7

x = 0
dx = 0.000001
(f(x+dx) - f(x) ) / dx

def df(x):
    dx = 0.000001
    return (f(x+dx) - f(x) ) / dx

df(1)

4.000000000559112

In [122]:
def f2(x):
    return 4*x**2 + 20*x -5

def df2(x):
    dx = 0.000001
    return (f2(x+dx) - f2(x) ) / dx

f2(5), df2(5)

(195, 60.00000399808414)

In [124]:
def df_g(f, x):
    dx = 0.000001
    return (f(x+dx) - f(x) ) / dx

def fun1(x):
    return 5*x + 7

df_g(fun1, 6)

5.000000001587068

In [125]:
def sig(x):
    return 1 / (1 + np.exp(-x))

                 1
        -----------------
           1 + exp(-x)

In [ ]:
x = 0               1 / (1 + exp(-0)  )  =  1 / (1 + 1) = 0.5
x = inf             1/ (1 + exp(-inf)  )  =  1 / (1 + 0) = 1
x = -inf           1/ (1 + exp(inf)  )  =  1 / 무한대  = 0 

In [127]:
df_g(sig, 100000)

0.0

In [ ]:
z = (7x1 + 4x2 - 6)^2

# 합성함수 미분
- (4x + 7)^2   ->    z = sx+7             2(4x+7)4

In [ ]:
 MSE = sum (wx + b - y)^2

 z = wx + b - y

MSE/dw =  2zx = 2(wx+b-y)x
MSE/db =  2z1 = 2(wx+b-y)

(wx+b-y)*x = 0
(wx+b-y) = 0

